<?php require __DIR__.'/includes/config.php';
$lowongan = $pdo->query("SELECT * FROM lowongan WHERE status='Aktif' ORDER BY id_lowongan DESC")->fetchAll();
?>
<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Portal Rekrutmen SDI Universitas</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="page-shell">
<nav class="public-nav"><div class="nav-inner"><a class="brand" href="index.php"><div class="brand-logo"><img src="assets/logo-kampus.png" alt="Logo Kampus"></div><div class="brand-title"><strong>Portal Rekrutmen SDI</strong><span>Universitas Muhammadiyah Banjarmasin</span></div></a><div class="nav-links"><a href="#lowongan">Lowongan</a><a href="#alur">Alur</a><a href="#syarat">Persyaratan</a><a class="btn btn-outline" href="login.php">Login</a><a class="btn btn-primary" href="register_pelamar.php">Daftar Akun</a></div></div></nav>
<header class="hero"><div class="hero-content"><div><span class="eyebrow">Portal resmi penerimaan dosen dan tenaga kependidikan</span><h1>Rekrutmen SDI yang tertib, transparan, dan terdokumentasi.</h1><p>Daftar akun, lengkapi data diri, unggah dokumen sesuai persyaratan, lalu pantau perkembangan lamaran melalui dashboard pelamar.</p><div class="hero-actions"><a class="btn btn-accent" href="register_pelamar.php">Daftar Sebagai Pelamar</a><a class="btn btn-outline" href="#lowongan">Lihat Lowongan</a></div></div><aside class="hero-panel"><h3>Informasi Seleksi</h3><ul class="mini-list"><li><span class="check-dot">✓</span><span>Lowongan dibedakan menjadi Dosen dan Tenaga Kependidikan.</span></li><li><span class="check-dot">✓</span><span>Dokumen pelamar diverifikasi oleh SDI sesuai checklist persyaratan.</span></li><li><span class="check-dot">✓</span><span>Surat panggilan tes, wawancara, dan penerimaan dikirim melalui email pelamar.</span></li></ul></aside></div></header>
<section class="section soft" id="lowongan"><div class="container"><div class="section-title"><div><h2>Lowongan Aktif</h2><p>Pilih posisi yang tersedia, lalu login untuk mengirim lamaran.</p></div><a class="btn btn-light" href="login.php">Login Pelamar</a></div><div class="grid"><?php if(!$lowongan): ?><div class="card"><h3>Belum ada lowongan aktif</h3><p>Silakan cek kembali halaman ini secara berkala.</p></div><?php else: foreach($lowongan as $l): ?><article class="card job-card"><div class="card-icon"><?= $l['kategori']==='Dosen' ? 'D' : 'T' ?></div><h3><?=e($l['nama_posisi'])?></h3><div class="job-meta"><span class="pill pill-blue"><?=e($l['kategori'])?></span><span class="pill pill-neutral">Min. <?=e($l['pendidikan_min'])?></span><span class="pill pill-neutral"><?=e($l['pengalaman_min'])?> tahun</span></div><p><?= $l['kategori']==='Dosen' ? 'Formasi dosen mengikuti persyaratan akademik dan administrasi sesuai pedoman.' : 'Formasi tenaga kependidikan mengikuti kebutuhan unit dan spesifikasi keahlian jabatan.' ?></p><a class="btn btn-primary" href="login.php">Login untuk Melamar</a></article><?php endforeach; endif; ?></div></div></section>
<section class="section" id="alur"><div class="container"><div class="section-title"><div><h2>Alur Rekrutmen</h2><p>Seluruh tahapan dibuat berurutan agar proses seleksi dapat dipantau dan dipertanggungjawabkan.</p></div></div><div class="stepper"><div class="step"><b>Daftar akun</b><p>Pelamar membuat akun menggunakan email aktif.</p></div><div class="step"><b>Kirim lamaran</b><p>Pelamar memilih lowongan dan mengunggah dokumen.</p></div><div class="step"><b>Verifikasi SDI</b><p>SDI mengecek kelengkapan dan kesesuaian berkas.</p></div><div class="step"><b>Tes & wawancara</b><p>Peserta mengikuti tahapan tes sesuai kategori lamaran.</p></div><div class="step"><b>Rekomendasi</b><p>Prodi/unit dan dekan memberi rekomendasi sesuai hasil seleksi.</p></div><div class="step"><b>Pengumuman</b><p>Informasi panggilan dan keputusan disampaikan melalui email.</p></div><div class="step"><b>Pembekalan</b><p>Calon pegawai mengikuti pembekalan dari pimpinan.</p></div><div class="step"><b>SK & penempatan</b><p>SK dan penempatan dicatat oleh pihak berwenang.</p></div></div></div></section>
<section class="section soft" id="syarat"><div class="container"><div class="section-title"><div><h2>Persyaratan Umum dan Administrasi</h2><p>Persyaratan dibedakan sesuai kategori lowongan.</p></div></div><div class="grid-2"><div class="card"><h3>Dosen</h3><div class="requirements"><div><b>Persyaratan umum</b><ul><li>Beragama Islam</li><li>Minimal S2</li><li>Berakhlak mulia dan berintegritas</li><li>Usia maksimal 58 tahun saat diangkat</li><li>Sehat jasmani dan rohani</li><li>Tidak menggunakan narkotika</li></ul></div><div><b>Administrasi</b><ul><li>Surat lamaran dan CV/biodata riwayat pengalaman kerja</li><li>Email aktif, fotokopi KTP, pas foto, fotokopi KK</li><li>Surat keterangan sehat</li><li>Fotokopi ijazah S1 dan S2 beserta transkrip</li><li>Fotokopi ijazah S3 beserta transkrip jika ada</li><li>SK penyetaraan ijazah opsional bagi lulusan luar negeri</li></ul></div></div></div><div class="card"><h3>Tenaga Kependidikan</h3><div class="requirements"><div><b>Persyaratan umum</b><ul><li>Beragama Islam</li><li>Pendidikan terakhir minimal SMA/sederajat</li><li>Sehat jasmani dan rohani</li><li>Sesuai spesifikasi keahlian yang ditentukan</li></ul></div><div><b>Administrasi</b><ul><li>Surat lamaran dan CV/biodata riwayat pengalaman kerja</li><li>Email aktif, fotokopi KTP, pas foto, fotokopi KK</li><li>Surat keterangan sehat</li><li>Fotokopi ijazah terakhir</li><li>Transkrip nilai terakhir</li><li>Sertifikat pendukung jika ada</li></ul></div></div></div></div></div></section>
<footer class="footer"><div class="container"><div><b>Portal Rekrutmen SDI</b><br><span>Universitas Muhammadiyah Banjarmasin</span></div><div>© <?=date('Y')?> Sistem Rekrutmen Dosen & Tenaga Kependidikan</div></div></footer>
</div></body></html>